version: "3"
services:
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/heroesAppMaster
    restart: always
    command: bash -c "npm install && npm run dev"
    volumes:
      - .:/usr/src/heroesAppMaster/
      - ./package.json:/usr/src/heroesAppMaster/package.json
    ports:
      - "8080:8080"
